### PR TITLE
Fixing charts post-go live bugs

### LINKED ISSUE #458: Group bar chart with select weird behavior
Grouped bar charts push content below them down really far for some reason.

### PR DESCRIPTION
**Pull request by paylakatel**
This PR: 
- fixes height with grouped bar charts
- should get rid of console errors on load
- updated vega-tooltip library

Fixes #458 and #457

### CODE REVIEW

File: web-components/chart/chart.tsx [hunk 1]
```diff
@@ -118,21 +118,31 @@ export class CobChart {
       */
       const legend = this.el.querySelector('div .mark-group .role-legend');
       const legendHeight = legend.getBoundingClientRect().height;
-      const calcHeight = this.config.height - legendHeight;
+      // We get the 'offset', or distance in px of the legend from the chart from the config.
+      // If there is no offset set, the default is 18 according to the Vega-Lite docs.
+      const offset = this.config.encoding.color.legend.offset
```
Comment (fionawhim) [inline web-components/chart/chart.tsx:124]: Do you need to check to make sure everything in this chain exists?

Comment (paylakatel) [reply web-components/chart/chart.tsx:124]: good call! Just updated 👍

Comment (fionawhim) [reply web-components/chart/chart.tsx:124]: Well done.

**Review by fionawhim — APPROVED** [review]

**Review by fionawhim — APPROVED** [review]
